name = "Remix Prisma Base App"
client_id = "${SHOPIFY_API_KEY}"
application_url = "${SHOPIFY_APP_URL}"
embedded = true
handle = "remix-prisma-base"

[build]
command = "npm run build"
deployment = "npm run start"

[webhooks]
api_version = "2024-07"

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback"
]

[app_proxy]
url = "${SHOPIFY_APP_URL}/proxy"
subpath = "app"
prefix = "apps"

[pos]
embedded = false
